name: sembast_test
description: Test helpers for sembast and sembast_web
version: 0.1.4
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.6.0
  sembast:
  sembast_web:
  test:
  # Dependencies for encryption example
  encrypt: '>=3.1.0'
  crypto: '>=2.0.6'
  pedantic:

dev_dependencies:
  http: '>=0.11.0'
  process_run: '>=0.10.2'
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'
  test_core:
  meta: '>=1.2.0'
  # Tool
  io:
  yaml:
  pub_semver:

dependency_overrides:
  # pedantic: '>=1.9.0'
  sembast:
    path: ../sembast
  sembast_web:
    path: ../sembast_web
